"""Backend Mapping Dictionary & Section Normalizer for AI Report Generation.

Decouples the LLM from having to memorize exact backend string identifiers
by mapping fuzzy user intent terms to canonical backend data sources, chart types,
and column definitions.
"""

import logging
import uuid
from typing import Any, Dict, List, Optional

from app.modules.reporting.services.report_localization import ReportLocalization

logger = logging.getLogger(__name__)

# Fuzzy term mappings to backend identifiers
CHART_MAPPING = {
    "reconciliation trend": "reconciliation_trend",
    "reconciliation": "reconciliation_trend",
    "anomaly distribution": "anomaly_distribution",
    "anomaly": "anomaly_distribution",
    "transaction volume": "transaction_volume",
    "volume": "transaction_volume",
    "bank vs erp": "bank_vs_erp",
    "revenue trend": "revenue_trend",
    "revenue": "revenue_trend",
    "cash flow": "cash_flow_trend",
}

KPI_MAPPING = {
    "revenue": "revenue",
    "expenses": "expenses",
    "cash flow": "cash_flow",
    "cash": "cash_flow",
    "reconciliation": "reconciliation_rate",
    "anomalies": "anomaly_stats",
    "overview": "overview",
}

TABLE_MAPPING = {
    "erp transactions": "erp_transactions",
    "transactions": "erp_transactions",
    "erp": "erp_transactions",
    "reconciliations": "reconciliation_records",
    "anomalies": "anomaly_records",
    "expenses": "expense_records",
}

DEFAULT_VISIBLE_COLUMNS = {
    "erp_transactions": ["invoice_id", "supplier", "invoice_date", "due_date", "amount", "currency", "status"],
    "reconciliation_records": ["reconciliation_id", "invoice_id", "matched_date", "amount", "status"],
    "anomaly_records": ["anomaly_id", "type", "severity", "detected_at", "amount", "status"],
    "expense_records": ["expense_id", "category", "vendor", "date", "amount", "currency"],
}

DEFAULT_RECOMMENDATIONS = [
    "Review reconciliation automation rules to increase automatic matching rate.",
    "Investigate high-severity transaction anomalies promptly.",
    "Monitor cash flow forecasts and manage outstanding unpaid invoices.",
    "Perform weekly bank statement reconciliations to reduce month-end lag.",
]


class SectionNormalizer:
    """Normalizes raw section JSON generated by LLM into fully-formed report definition objects."""

    @staticmethod
    def normalize_sections(raw_sections: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Normalize a list of raw sections."""
        normalized: List[Dict[str, Any]] = []

        for position, sec in enumerate(raw_sections, 1):
            if not isinstance(sec, dict):
                continue

            sec_type = sec.get("type", "text")
            config = sec.get("config", {}) or {}

            norm_sec = {
                "id": sec.get("id") or f"sec_{sec_type}_{uuid.uuid4().hex[:6]}",
                "type": sec_type,
                "position": position,
                "config": SectionNormalizer._normalize_config(sec_type, config),
            }
            normalized.append(norm_sec)

        return normalized

    @staticmethod
    def _normalize_config(sec_type: str, config: Dict[str, Any]) -> Dict[str, Any]:
        norm = dict(config)

        if sec_type == "chart":
            title = (norm.get("title") or "Financial Chart").lower()
            chart_type = norm.get("chart_type")

            if not chart_type:
                # Match title or concept to CHART_MAPPING
                for key, val in CHART_MAPPING.items():
                    if key in title:
                        chart_type = val
                        break
                if not chart_type:
                    chart_type = "reconciliation_trend"

            norm["chart_type"] = chart_type
            # chart_type may be a matplotlib render type (line, bar, pie, donut, grouped_bar).
            # If data_source is missing, do NOT blindly reuse chart_type as data_source,
            # because render types are not valid analytics chart keys.
            _VALID_RENDER_TYPES = {"line", "bar", "grouped_bar", "pie", "donut"}
            if not norm.get("data_source"):
                if chart_type in _VALID_RENDER_TYPES:
                    norm["data_source"] = "reconciliation_trend"
                else:
                    norm["data_source"] = chart_type
            norm["title"] = config.get("title") or chart_type.replace("_", " ").title()
            logger.info(
                "[MAPPER] Normalized chart | chart_type=%s | data_source=%s | title=%s",
                chart_type, norm["data_source"], norm["title"]
            )

        elif sec_type == "table":
            title = (norm.get("title") or "Data Table").lower()
            data_source = norm.get("data_source")

            if not data_source:
                for key, val in TABLE_MAPPING.items():
                    if key in title:
                        data_source = val
                        break
                if not data_source:
                    data_source = "erp_transactions"

            norm["data_source"] = data_source
            norm["title"] = config.get("title") or data_source.replace("_", " ").title()

            if not norm.get("visible_columns"):
                norm["visible_columns"] = DEFAULT_VISIBLE_COLUMNS.get(data_source, ["invoice_id", "supplier", "amount", "status"])
            # Only apply a default limit when the user/LLM did not specify one.
            # Explicit user limits must never be overridden.
            if norm.get("limit") is None:
                norm["limit"] = 20
            logger.info(
                "[MAPPER] Normalized table | data_source=%s | limit=%s | title=%s",
                data_source, norm.get("limit"), norm["title"]
            )

        elif sec_type == "kpi":
            title = (norm.get("title") or "Key Metrics").lower()
            # Preserve explicit data_source/kpi_key from the LLM or frontend
            data_source = (
                norm.get("data_source")
                or norm.get("kpi_key")
                or config.get("data_source")
                or config.get("kpi_key")
            )

            if not data_source:
                for key, val in KPI_MAPPING.items():
                    if key in title:
                        data_source = val
                        break
                if not data_source:
                    data_source = "revenue"

            norm["data_source"] = data_source
            norm["kpi_key"] = data_source
            norm["title"] = config.get("title") or f"{data_source.replace('_', ' ').title()} KPIs"
            logger.info(
                "[MAPPER] Normalized kpi | data_source=%s | kpi_key=%s | title=%s",
                data_source, norm["kpi_key"], norm["title"]
            )

        elif sec_type == "recommendation":
            norm["title"] = norm.get("title") or "Executive Recommendations"
            if not norm.get("recommendations") and not norm.get("items"):
                # Use localized fallback recommendations based on report language
                language = (config.get("language") or "en").strip().lower()
                norm["recommendations"] = ReportLocalization.fallback_recommendations(language)
            logger.info(
                "[MAPPER] Normalized recommendation | title=%s | count=%d",
                norm["title"], len(norm.get("recommendations", []))
            )

        elif sec_type == "text":
            norm["title"] = norm.get("title") or "Executive Overview"
            if not norm.get("content"):
                norm["content"] = "This report section provides executive analysis and financial commentary for the evaluated period."

        elif sec_type == "ai_insight":
            norm["insight_type"] = norm.get("insight_type") or norm.get("topic") or "trend_analysis"
            norm["title"] = norm.get("title") or "AI Financial Insights"

        return norm
