"""Regression tests for AI report prompt leakage and table row limits.

Tests cover:
    Test A: PDF export does not render user instruction phrases when description is clean
    Test B: ReportDataResolver passes config.limit to AnalyticsService
    Test C: ExportEngine._render_table applies config.limit when rendering rows
"""

import os
import sys
import tempfile
import unittest
from unittest.mock import patch

# Ensure the backend app is importable
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app.modules.reporting.services.export_engine import ExportEngine
from app.modules.reporting.services.report_data_resolver import ReportDataResolver


def _extract_pdf_text(file_path: str) -> str:
    """Extract all text from a PDF using PyMuPDF (fitz)."""
    import fitz  # PyMuPDF

    doc = fitz.open(file_path)
    text = ""
    for page in doc:
        text += page.get_text()
    doc.close()
    return text


class TestPromptLeakageRegression(unittest.TestCase):
    """Regression tests ensuring user prompts never appear in exported PDFs."""

    def _generate_pdf(self, report_data):
        """Generate a PDF and return the file path."""
        file_path = os.path.join(tempfile.gettempdir(), f"test_regression_{id(report_data)}.pdf")
        ExportEngine._generate_pdf(report_data, file_path)
        self.assertTrue(os.path.exists(file_path), "PDF file was not created")
        self.assertGreater(os.path.getsize(file_path), 0, "PDF file is empty")
        return file_path

    def _cleanup(self, file_path):
        """Remove a generated test file."""
        if os.path.exists(file_path):
            os.remove(file_path)

    # ------------------------------------------------------------------
    # Test A: Clean description does not leak instruction phrases
    # ------------------------------------------------------------------

    @patch("app.modules.reporting.services.export_engine.ReportDataResolver.resolve")
    def test_a_clean_description_no_prompt_leak(self, mock_resolve):
        """Test A: A report with a clean business description must not render user instructions."""
        mock_resolve.return_value = {
            "title": "ERP Transactions",
            "data": [
                {"invoice_id": "INV-001", "supplier": "Acme", "amount": 100.0, "status": "paid"},
            ],
        }

        # This simulates the fixed frontend: description is a clean business subtitle,
        # NOT the user's objective/instruction text.
        report = {
            "name": "Q2 Financial Performance Review",
            "description": "Executive financial analysis generated by the AI Report Builder.",
            "definition": {
                "sections": [
                    {
                        "type": "table",
                        "config": {"title": "ERP Transactions", "data_source": "erp_transactions"},
                    }
                ]
            },
        }

        file_path = self._generate_pdf(report)
        try:
            pdf_text = _extract_pdf_text(file_path)
        finally:
            self._cleanup(file_path)

        # The user's original instruction phrases must NEVER appear in the PDF
        forbidden_phrases = [
            "Create a professional executive financial report",
            "The report should demonstrate every supported section type",
            "Structure the report as follows",
            "Use this image",
            "Only display",
            "Limit to first",
        ]
        for phrase in forbidden_phrases:
            self.assertNotIn(
                phrase.lower(),
                pdf_text.lower(),
                f"User instruction phrase leaked into PDF: '{phrase}'",
            )

        # The report title and clean description SHOULD appear
        self.assertIn("Q2 Financial Performance Review", pdf_text)
        self.assertIn("Executive financial analysis", pdf_text)

    # ------------------------------------------------------------------
    # Test B: Resolver respects config.limit
    # ------------------------------------------------------------------

    @patch("app.modules.reporting.services.analytics_service.AnalyticsService.get_table_data")
    def test_b_resolver_respects_config_limit(self, mock_get_table_data):
        """Test B: ReportDataResolver must pass config.limit to AnalyticsService."""
        all_rows = [{"id": i} for i in range(1, 6)]  # 5 rows

        def fake_get_table_data(data_source, date_from=None, date_to=None, limit=None):
            if limit:
                return all_rows[:limit]
            return all_rows

        mock_get_table_data.side_effect = fake_get_table_data

        section = {
            "type": "table",
            "config": {
                "data_source": "erp_transactions",
                "limit": 2,
            },
        }

        result = ReportDataResolver.resolve(section, None, None)

        # Verify the limit was passed through to AnalyticsService
        mock_get_table_data.assert_called_once()
        call_args = mock_get_table_data.call_args
        self.assertEqual(call_args[0][0], "erp_transactions")
        self.assertEqual(
            call_args[1].get("limit"),
            2,
            "config.limit=2 was not passed to AnalyticsService",
        )

        # Result data should be limited to 2 rows
        self.assertEqual(len(result["data"]), 2, "Resolver should return only 2 rows")

    # ------------------------------------------------------------------
    # Test C: PDF rendering applies config.limit
    # ------------------------------------------------------------------

    @patch("app.modules.reporting.services.export_engine.ReportDataResolver.resolve")
    def test_c_pdf_table_respects_limit(self, mock_resolve):
        """Test C: _render_table must apply config.limit when rendering rows."""
        mock_resolve.return_value = {
            "title": "ERP Transactions",
            "data": [
                {
                    "invoice_id": f"INV-{i:03d}",
                    "supplier": f"Supplier {i}",
                    "amount": float(i * 100),
                    "status": "paid",
                }
                for i in range(1, 51)  # 50 rows
            ],
        }

        report = {
            "name": "Limited Table Report",
            "description": "Table limit test",
            "definition": {
                "sections": [
                    {
                        "type": "table",
                        "config": {
                            "title": "ERP Transactions",
                            "data_source": "erp_transactions",
                            "limit": 20,
                        },
                    }
                ]
            },
        }

        file_path = self._generate_pdf(report)
        try:
            pdf_text = _extract_pdf_text(file_path)
        finally:
            self._cleanup(file_path)

        # The footer should say "Showing 20 of 20 records" (not 50)
        self.assertIn("Showing 20 of 20 records", pdf_text)

        # The 21st row (INV-021) should NOT appear in the PDF
        self.assertNotIn("INV-021", pdf_text)


if __name__ == "__main__":
    unittest.main()
